#!/data/data/com.termux/files/usr/bin/bash
# REMOVE BANNER,LOGIN

clear
#Remove Banner
remove_banner() {

# Remove T-modern-look Banner 
# save old login

# change dir to ~
cd $HOME
cd T-modern-look
cd remove

# moving default bash.bashcrc to ~
mv bash.bashrc $HOME 

# remove T-modern-look bash.bashrc
cd  /data/data/com.termux/files/usr/etc
rm bash.bashrc

# change dir to home
cd $HOME
cd T-modern-look

echo
echo ">>> Removing T-modern-look Banner" |lolcat
bash ashi.sh
cd $HOME

# replace default bash.bashrc
mv bash.bashrc /data/data/com.termux/files/usr/etc

echo 
echo -e "\e[33m[\e[31m*\e[33m]\e[33m Open a new Session \e[m" 
echo
sleep 1
echo -e  "\e[33m[\e[31m*\e[33m]\e[33m Successfully Removed the banner \e[m "
sleep 2
}

# Remove login
remove_login() {
# remove Password login
# save default motd login

cd $HOME
cd /data/data/com.termux/files/usr/etc
rm -rf motd 
cd $HOME
cd T-modern-look
cd remove
cp motd /data/data/com.termux/files/usr/etc
rm $PREFIX/bin/login.py
cp old_login $PREFIX/bin/login
chmod 700 $PREFIX/bin/login
echo 
cd $HOME/T-modern-look
echo ">>> Removing T-modern-look login " |lolcat
bash ashi.sh
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Removing T-modern-look \e[m "
sleep 2
echo
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Loading\e[m "
sleep 3
echo
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Successfully Removed Login\e[m "
sleep 2
}


while :
do
echo
echo
echo "[~] select the option to remove" | lolcat
echo
echo "1) Remove Banner" |lolcat
echo
echo "2) Remove Login" |lolcat
echo
echo "3) All " |lolcat
echo
echo

read -p  $'\e[31m[\e[32m*\e[31m]\e[32m choose your option :\e[m ' option

if [ $option = 1 ] || [ $option = 01 ]
then
remove_banner
break

elif [ $option = 2 ] || [ $option = 02 ]
then
remove_login
break

elif [ $option = 3 ] || [ $option = 03 ]
then
remove_banner
remove_login
break

else
echo
echo "[!] Invalid option try again" |lolcat
sleep 2
fi
done

# like subscribe channel
clear
tput clear
tput cup 3 30
echo -en "\e[93m what is your name : \e[m"
read answer
tput cup 6 30
echo -e "\e[104m hello! Open a New session!! $answer! \e[m"
echo
figlet -f slant "DUMPED ONE" |lolcat
echo
